version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $REPOSITORY_URI
      - aws --version
      - aws ecr get-login --region us-east-1 --no-include-email
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=298973770113.dkr.ecr.us-east-1.amazonaws.com/springbootdemo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Building the Docker image...
      - docker build -t 298973770113.dkr.ecr.us-east-1.amazonaws.com/springbootdemo:latest .
      - echo Tagging Docker image...
      - docker tag 298973770113.dkr.ecr.us-east-1.amazonaws.com/springbootdemo:latest 298973770113.dkr.ecr.us-east-1.amazonaws.com/springbootdemo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 298973770113.dkr.ecr.us-east-1.amazonaws.com/springbootdemo:latest
